export const postDataGenerate = {
  competency_generate_type: 'USE_OLD',
  competency_number: 2,
  artifact_generate_type: 'USE_OLD',
  artifact_number: 2,
  event_generate_type: 'USE_OLD',
  event_number: 2,
  event_artifact_generate_type: 'USE_OLD',
  event_artifact_number: 2,
  event_competency_generate_type: 'USE_OLD',
  event_competency_number: 2,
  game_world_story_generate_type: 'USE_OLD',
  game_world_story_number: 2,
  mission_generate_type: 'USE_OLD',
  mission_number: 2,
  mission_artifact_generate_type: 'USE_OLD',
  mission_artifact_number: 2,
  mission_competency_generate_type: 'USE_OLD',
  mission_competency_number: 2,
  mission_branch_generate_type: 'USE_OLD',
  mission_branch_number: 2,
}
